### ISSUE TITLE
npm run dev

### ISSUE THREAD

**Issue by LaurentD87** [sveltejs/template#121]
Hello,

I installed the last stable version of Node and followed the tutorial from the website. The command `npm run dev` throws the following error (copying the log here):
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'start', '--', '--dev' ]
2 info using npm@6.13.4
3 info using node@v12.16.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle svelte-app@1.0.0~prestart: svelte-app@1.0.0
6 info lifecycle svelte-app@1.0.0~start: svelte-app@1.0.0
7 verbose lifecycle svelte-app@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle svelte-app@1.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/laurent/svelpte-app/node_modules/.bin:/usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/laurent/svelpte-app/node_modules/.bin:/home/laurent/anaconda3/bin:/home/laurent/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle svelte-app@1.0.0~start: CWD: /home/laurent/svelpte-app
10 silly lifecycle svelte-app@1.0.0~start: Args: [ '-c', 'sirv public "--dev"' ]
11 silly lifecycle svelte-app@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle svelte-app@1.0.0~start: Failed to exec start script
13 verbose stack Error: svelte-app@1.0.0 start: `sirv public "--dev"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:311:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:311:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid svelte-app@1.0.0
15 verbose cwd /home/laurent/svelpte-app
16 verbose Linux 5.3.0-42-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "start" "--" "--dev"
18 verbose node v12.16.1
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error svelte-app@1.0.0 start: `sirv public "--dev"`
22 error Exit status 1
23 error Failed at the svelte-app@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by mvllow** [comment]
could be related to https://github.com/webpack/webpack/issues/8254

try removing node_modules and running `npm install` again

**Comment by LaurentD87** [comment]
That didn't help. :(

**Comment by LaurentD87** [comment]
I found the problem. My `$HOST` environment variable had been set to something that sirv did not recognize, probably by some python process (the value had 'anaconda' in it). I just did `unset HOST` and now it works just fine.

**Comment by arxpoetica** [comment]
Closing since you solved the problem locally (not a svelte template issue).
