### ISSUE TITLE
Fails to run dev, build scripts on fresh install

### ISSUE THREAD

**Issue by Splode** [sveltejs/template#136]
## Expected Behavior

Running `npm run dev` and `npm run start` successfully starts the dev server or builds production assets.

## Actual Behavior

```sh
λ npm run dev

> svelte-app@1.0.0 dev C:\Users\Christopher\code\svelte-app
> rollup -c -w

[!] Error: No valid exports main found for 'C:\Users\Christopher\code\svelte-app\node_modules\@rollup\pluginutils'
Error: No valid exports main found for 'C:\Users\Christopher\code\svelte-app\node_modules\@rollup\pluginutils'
    at resolveExportsTarget (internal/modules/cjs/loader.js:618:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:650:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:948:27)
    at Function.Module._load (internal/modules/cjs/loader.js:854:27)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\Christopher\code\svelte-app\node_modules\@rollup\plugin-node-resolve\dist\index.js:15:19)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
```

## Steps to Reproduce

1. Clone repo
2. Run `npm install`
3 Run `npm run dev` or `npm run build`

## Notes

Using node `v13.3.0` with npm `v6.13.1` on Windows 10. This happens on a fresh install, with no changes to the codebase.

**Edit:** using the latest node LTS `v12.18.0` works as expected.

**Comment by maximusunc** [comment]
I'm also having this issue on Mac 10.15.5, node v13.2.0 and npm v6.13.1.

**Comment by mathiasmagnusson** [comment]
I have the same issue on Linux (Pop OS 20.04) and node v13.5, npm 6.14.4, except the error is for `@rollup/plugin-node-resolve`

**Comment by antony** [comment]
This issue only occurs with node v13.5, so there's clearly an issue with that release.

It works fine with:
v13.14
v12
v14

So the solution is to just use a newer version of nodejs. Ideally LTS.
