### ISSUE TITLE
Unexpected token function

### ISSUE THREAD

**Issue by nevillekelly** [sveltejs/template#61]
Steps I have taken

1. Unzipped the REPL package from https://svelte.dev into project folder
2. Ran 'npm install'
3. Ran 'npm run build'

Get the following error:
`PS D:\Projects\GitHub\MediaSwitcher> npm run build

> svelte-app@1.0.0 build D:\Projects\GitHub\MediaSwitcher
> rollup -c

[!] SyntaxError: Unexpected token function
D:\Projects\GitHub\MediaSwitcher\node_modules\svelte\compiler.js:23956
        async function replace_async(str, re, func) {
              ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions..js (D:\Projects\GitHub\MediaSwitcher\node_modules\rollup\dist\bin\rollup:841:17)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! svelte-app@1.0.0 build: `rollup -c`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the svelte-app@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nev\AppData\Roaming\npm-cache\_logs\2019-09-09T23_01_30_133Z-debug.log
PS D:\Projects\GitHub\MediaSwitcher>`

**Comment by Conduitry** [comment]
Svelte needs at least Node 8. I'm guessing you have an older version? Node 6 has been at end-of-life since earlier this year, so you should be updating anyway.
